- name: General | Install Application packages
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl

- name: vTiger | Ensure MySQL is running
  service: 
    name: mysql 
    state: started

- name: vTiger | Create vTiger database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ vtiger_db_name }}"
    state: present

- name: vTiger | Create vTiger database user
  mysql_user:
    name: "{{ vtiger_db_user }}"
    password: "{{ vtiger_db_password }}"
    priv: "{{ vtiger_db_name }}.*:ALL,GRANT"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: vTiger | Download application from Github
  sudo: false
  git: >
    repo=https://github.com/maestrano/vtiger6.git
    dest={{ vtiger_root_path }}
    version=6.2.0-1
    accept_hostkey=yes
    ssh_opts="-o StrictHostKeyChecking=no"
    update=yes
    force=yes

- name: vTiger | Configure Apache virtual host
  template: 
    src: etc-apache24-confd-vtiger6-conf
    dest: /etc/apache2/sites-available/vtigercrm.conf
    owner: root
    mode: 755

- name: vTiger | Enable Apache virtual host 
  file: src=/etc/apache2/sites-available/vtigercrm.conf dest=/etc/apache2/sites-enabled/vtigercrm.conf state=link

- name: Apache | Restart the Apache service
  service: 
    name: apache2 
    state: restarted

- name: vTiger | Configuration file config.php
  template: 
    src: vtiger-config.inc.php
    dest: "{{ vtiger_root_path }}/config.inc.php"
    owner: root
    mode: 755

- name: vTiger | Configuration file app_setup.php
  copy: 
    src: vtiger-app_setup.php
    dest: "{{ vtiger_root_path }}/app_setup.php"
    owner: root
    mode: 755

- name: vTiger | Configuration file user_privileges
  copy: 
    src: "{{ item }}"
    dest: "{{ vtiger_root_path }}/user_privileges/{{ item }}"
    owner: root
    mode: 755
  with_items:
    - sharing_privileges_1.php
    - user_privileges_1.php

- name: vTiger | Configuration file maestrano.json
  template: 
    src: vtiger-maestrano.json
    dest: "{{ vtiger_root_path }}/maestrano.json"
    owner: www-data
    group: www-data
    mode: 777
  tags:
    - configuration

- name: vTiger | Setup Application
  shell: "php {{ vtiger_root_path }}/app_setup.php"
  args:
    chdir: "{{ vtiger_root_path }}"

- name: vTiger | Apply Maestrano patch
  shell: "mysql {{ vtiger_db_name }} -u{{vtiger_db_user}} -p{{vtiger_db_password}} < maestrano/app/db/1_add_mno_uid_field.sql"
  args:
    chdir: "{{ vtiger_root_path }}"

- name: vTiger | Set file permissions
  file: "path={{ vtiger_root_path }} mode=755 owner=www-data group=www-data state=directory recurse=yes"